# vim: set ft=yaml ts=2 expandtab:
---

- debug: var=php_fpm_package
  tags:
  - never
  - debug

- debug: var=php_fpm_service
  tags:
  - never
  - debug

- debug: var=etcdir
  tags:
  - never
  - debug

- debug: msg="{{ extensions + [ php_fpm_package ] }}"
  tags:
  - never
  - debug

- debug: var=etcdir
  tags:
  - never
  - debug

- name: debug packages
  debug: msg="{{ (extensions if (scl == false) else extensions|map('regex_replace', '(.*)', scl + '-\\1')|list) + [ php_fpm_package ] }}"
  tags:
  - never
  - debug

- name: assertions for pool config
  loop: "{{ php_fpm_pools }}"
  assert:
    that:
      - item.name is defined
      - item.user is defined
      - item.group is defined

- name: php-fpm is installed
  package:
    name: "{{ (extensions if (scl == false) else extensions|map('regex_replace', '(.*)', scl + '-\\1')|list) + [ php_fpm_package ] }}"


- name: directory for log files are present
  when: php_fpm_pools is defined
  loop: "{{ php_fpm_pools }}"
  file:
    path: "{{ vardir }}/log/{{ item.name }}"
    state: directory
    owner: "{{ item.user }}"
    group: root
    setype: httpd_var_lib_t 
    mode: 0770

- name: directories for data are present
  when: php_fpm_pools is defined
  loop: "{{ php_fpm_pools|product(['session','wsdlcache'])|list }}"
  file:
    path: "{{ vardir }}/lib/php/{{ item[0].name }}/{{ item[1] }}"
    state: directory
    owner: root
    group: "{{ item[0].group }}"
    setype: httpd_var_run_t
    mode: 0770

- name: directories for data are present
  when: php_fpm_pools is defined
  loop: "{{ php_fpm_pools }}"
  file:
    path: "{{ vardir }}/lib/php/{{ item.name }}/opcache"
    state: directory
    owner: root
    group: "{{ item.group }}"
    setype: httpd_var_lib_t 
    mode: 0770

- name: pool configs are present
  when: php_fpm_pools is defined
  loop: "{{ php_fpm_pools }}"
  loop_control:
    loop_var: pool
  template:
    src: pool.conf.j2
    dest: "{{ etcdir }}/php-fpm.d/{{ pool.name }}.conf"
    backup: true
  notify: reload php-fpm

- name: placeholder for pool www is present
  when:
  - php_fpm_pools is defined
  - not 'www' in php_fpm_pools
  copy:
    content: '; placeholder'
    dest: "{{ etcdir }}/php-fpm.d/www.conf"
  notify: reload php-fpm
    
- name: php-fpm service is running
  service:
    name: "{{ php_fpm_service }}"
    state: started
  register: _php_fpm_was_started

- debug: var=_php_fpm_was_started
  tags:
  - never
  - debug

- name: logrotate for pools is present
  template:
    src: logrotate-pool.j2
    dest: /etc/logrotate.d/{{ scl|default('php-fpm') }}-pools
    
...
